### PR TITLE
Update regula version to 2.5.0

### PR DESCRIPTION
**Pull request by nsarupr**
# Description
Update the regula version.

# Safety checklist
* [ ] This change is backwards compatible and safe to apply by existing users
* [ ] This change will NOT lead to data loss
* [ ] This change will NOT lead to downtime who already has an env/service setup

## How has this change been tested, beside unit tests?
Tested Regula manually on the System.

### CODE REVIEW

**Review by bigbitbus — COMMENTED** [review]
The new version causes some tests to fail; you may want to (1) either fix the RC on the failed tests - but this means testing that the change in TF is backward compatible and doesnt cause infra to be torn down and spun up OR (2) Add more exceptions to the config/config.rego.

**Comment by nsarupr** [comment]
> The new version causes some tests to fail; you may want to (1) either fix the RC on the failed tests - but this means testing that the change in TF is backward compatible and doesnt cause infra to be torn down and spun up OR (2) Add more exceptions to the config/config.rego.

@bigbitbus for this, I am not sure which one would be the better way to go forward with, it depends upon the errors and how we want to get through these. Shall we have a discussion this monday, to figure out which ones do we need to waive and which ones do we need to add and make those backward compatible.

**Review by bigbitbus — APPROVED** [review]
lgtm

**Comment by bigbitbus** [comment]
@nsarupr you may close this since regula has been removed from the repo and github.

**Comment by rabbitfang** [comment]
Superseded by #837

**Pull request closed without merging**
