### PR TITLE
Delete cert manager helm

### PR DESCRIPTION
**Pull request by nsarupr**
# Description
Delete Cert Manager Helm chart.

# Safety checklist
* [ ] This change is backwards compatible and safe to apply by existing users
* [ ] This change will NOT lead to data loss
* [ ] This change will NOT lead to downtime who already has an env/service setup

## How has this change been tested, beside unit tests?
Tested Manually on AWS with `full stack example` and `hello opta`

[CI test here](https://app.circleci.com/pipelines/github/run-x/opta/1891/workflows/2d9dbb70-ce5d-4bab-bf70-53b55326ac1e)

### CODE REVIEW

**Review by RemyDeWolf — CHANGES_REQUESTED** [review]
let's hold on this one, I was reviewing the code, and I think we might need this.
In the doubt, let's wait for JD before we merge this.

I think we might be using this https://kubernetes.github.io/ingress-nginx/user-guide/tls/#automated-certificate-management-with-cert-manager

**Comment by NitinAgg** [comment]
@juandiegopalomino can you take a look at this PR

**Review by juandiegopalomino — APPROVED** [review]
Should be fine, make sure to test

**Comment by nsarupr** [comment]
Duplicates  #823 and #795

**Pull request closed without merging**
